// All Topics Start
export const ALL_TOPICS_DETAILS_REQUEST = "ALL_TOPICS_DETAILS_REQUEST";
export const ALL_TOPICS_DETAILS_SUCCESS = "ALL_TOPICS_DETAILS_SUCCESS";
export const ALL_TOPICS_DETAILS_FAIL = "ALL_TOPICS_DETAILS_FAIL";
// All Topics End

// Clear Errors Start
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// Clear Errors End

// React JS Start
export const ALL_TOPICS_REACTJS_REQUEST = "ALL_TOPICS_REACTJS_REQUEST";
export const ALL_TOPICS_REACTJS_SUCCESS = "ALL_TOPICS_REACTJS_SUCCESS";
export const ALL_TOPICS_REACTJS_FAIL = "ALL_TOPICS_REACTJS_FAIL";

export const ALL_QSTNS_REACTJS_REQUEST = "ALL_QSTNS_REACTJS_REQUEST";
export const ALL_QSTNS_REACTJS_SUCCESS = "ALL_QSTNS_REACTJS_SUCCESS";
export const ALL_QSTNS_REACTJS_FAIL = "ALL_QSTNS_REACTJS_FAIL";

export const ALL_MCQ_REACTJS_REQUEST = "ALL_MCQ_REACTJS_REQUEST";
export const ALL_MCQ_REACTJS_SUCCESS = "ALL_MCQ_REACTJS_SUCCESS";
export const ALL_MCQ_REACTJS_FAIL = "ALL_MCQ_REACTJS_FAIL";
// React JS End


// JavaScript Start
export const ALL_QSTNS_JAVASCRIPT_REQUEST = "ALL_QSTNS_JAVASCRIPT_REQUEST";
export const ALL_QSTNS_JAVASCRIPT_SUCCESS = "ALL_QSTNS_JAVASCRIPT_SUCCESS";
export const ALL_QSTNS_JAVASCRIPT_FAIL = "ALL_QSTNS_JAVASCRIPT_FAIL";
// JavaScript End

// NodeJS Start
export const ALL_QSTNS_NODEJS_REQUEST = "ALL_QSTNS_NODEJS_REQUEST";
export const ALL_QSTNS_NODEJS_SUCCESS = "ALL_QSTNS_NODEJS_SUCCESS";
export const ALL_QSTNS_NODEJS_FAIL = "ALL_QSTNS_NODEJS_FAIL";
// NodeJS End