export const ALL_TOPICS_DETAILS_REQUEST = "ALL_TOPICS_DETAILS_REQUEST";
export const ALL_TOPICS_DETAILS_SUCCESS = "ALL_TOPICS_DETAILS_SUCCESS";
export const ALL_TOPICS_DETAILS_FAIL = "ALL_TOPICS_DETAILS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
